/* Autogenerated by png2wx.pl on Mon Nov  4 11:20:10 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_noaadoppler_active;
extern wxBitmap *_img_noaadoppler_inactive;

#endif /* ICONS_H */
